[package]
name = "readable-stream"
description = "async readable streams built on tokio and Futures"
version = "0.0.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
license = "MIT"

[dependencies]
